### ISSUE TITLE
Spaces in file name causes error

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/ppp-web#5]
## Description
If a user attempts to convert a file with spaces in it, everything after the space is not considered. It tries to convert a file that therefore does not exist and also has no file extension, and it errors.

**Comment by tulvit** [comment]
**tldr:** solved, please, check the "develop-spaces-issue" branch.

### Problem
Filenames were used as a parameters for a shell execution, and they were used "as is" without any pre-processing, so extra spaces just ruins the command.

### Solution
Shell escaping string. I assume you use Python 3.3 or higher, so I've imported/used [shlex module](https://docs.python.org/dev/library/shlex.html#shlex.quote).

Comparing changes: [develop vs develop-spaces-issue](https://github.com/PMA-2020/ppp-web/compare/develop...develop-spaces-issue)

**Comment by joeflack4** [comment]
Hey Vitaly. This is awesome, thanks. I will test to confirm the fix shortly!

**Comment by joeflack4** [comment]
Confirmed fixed. Sorry for the delay. Very happy with this fix ^^

**Comment by joeflack4** [comment]
Going to merge this into develop.
