### ISSUE TITLE
Dependency update: odk-ppp

### ISSUE THREAD

**Issue by joeflack4** [PMA-2020/ppp-web#8]
## Description
In requirements.txt, ppp-web is currently using an old requirement: `https://github.com/joeflack4/pmix/zipball/working_ppp`

This line should now be: `odk-ppp`

## Tasks
- [x] Update the requirements, and do `pip3 install -r requirements.txt` (possibly may need to add the `--upgrade` flag, I'm not sure).
- [x] Test manually to make sure things work. Try converting some files.

**Comment by tulvit** [comment]
Done, tested. Works like a charm:

`$ python3 -m ppp 1.xlsx -p minimal > 1.html
/usr/bin/python3: No module named ppp
$ pip3 install -r https://raw.githubusercontent.com/PMA-2020/ppp-web/develop-readme/requirements.txt
$ python3 -m ppp 1.xlsx -p minimal > 1.html`
_*and it produced a valid file_

Also, please check my edits to README.md file.

[Changes](https://github.com/PMA-2020/ppp-web/compare/develop-readme) - probably, both files (README.md and requirements.txt) could be merged to a development branch.

**Comment by joeflack4** [comment]
@tulvit Thanks!

Changes merged in #10
